# Import Python module 

In [3]:
import pandas as pd
import numpy as np

from imblearn.ensemble import RUSBoostClassifier

from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import accuracy_score,recall_score ,precision_score

Using TensorFlow backend.


# 1. SMOTENC.csv

* read csv

In [10]:
traindata = pd.read_csv("SMOTENC.csv")

In [11]:
testdata = pd.read_csv("feature_select_test_set.csv")

In [13]:
traindata.head()

BP7  D_1_1  BP1  LW_mp_a    ainc  DC6_dg  BP6_10  HE_wt   age  EC1_2  \
0  8.0    1.0  8.0    888.0   500.0     8.0     8.0   19.5   3.0    8.0   
1  2.0    4.0  3.0    999.0   314.0     0.0     2.0   66.9  76.0    5.0   
2  2.0    3.0  3.0    999.0   700.0     8.0     2.0   48.7  12.0    8.0   
3  8.0    2.0  3.0    888.0  1009.0     0.0     2.0   54.1  38.0    8.0   
4  2.0    2.0  1.0    888.0   500.0     8.0     2.0   45.8  14.0    8.0   

       ...       HE_obe  BM1_4  BO2_1  HE_Uph  EC_lgw_2  DE1_4  BD2_31  \
0      ...          9.0    8.0    8.0     9.0      88.0    8.0     8.0   
1      ...          2.0    0.0    1.0     6.5       7.0    8.0     4.0   
2      ...          9.0    0.0    4.0     6.0      88.0    8.0     8.0   
3      ...          2.0    1.0    3.0     5.0       3.0    8.0     3.0   
4      ...          9.0    1.0    1.0     6.5      88.0    8.0     8.0   

    BS6_2  DH2_dg  Is_Depressed  
0  8888.0     9.0             0  
1   480.0     1.0             0  
2  8888.0     8.0             0  
3  8888.0     9.0             0  
4  8888.0     8.0             0  

[5 rows x 58 columns]

In [14]:
train_X = traindata.drop(["Is_Depressed"],axis = 1)
train_y = traindata["Is_Depressed"]

test_X = testdata.drop(["Is_Depressed"],axis = 1)
test_y = testdata["Is_Depressed"]

In [15]:
print(sorted(Counter(train_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 28639), (1, 28639)]
[(0, 7166), (1, 148)]


In [71]:
classifier = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 10),
    algorithm="SAMME",
    n_estimators=200
)

In [73]:
scores = cross_val_score(classifier, test_X, test_y, cv=10, scoring='recall')
print(scores)

[0.         0.         0.         0.06666667 0.         0.
 0.         0.06666667 0.         0.        ]


In [74]:
classifier.fit(train_X, train_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=10,
                           

In [64]:
predictions = classifier.predict(test_X)

###

In [65]:
confusion_matrix(test_y, predictions)

array([[7114,   52],
       [ 108,   40]], dtype=int64)

In [66]:
print("정확도",accuracy_score(test_y, predictions))
print("Recall",recall_score(test_y, predictions))
print("Precision",precision_score(test_y,predictions))

정확도 0.9781241454744326
Recall 0.2702702702702703
Precision 0.43478260869565216


###

In [47]:
confusion_matrix(test_y, predictions)

array([[7090,   76],
       [ 107,   41]], dtype=int64)

In [48]:
print("정확도",accuracy_score(test_y, predictions))
print("Recall",recall_score(test_y, predictions))
print("Precision",precision_score(test_y,predictions))

정확도 0.9749794913863823
Recall 0.27702702702702703
Precision 0.3504273504273504


# 2. no_na_SMOTENC.csv

In [21]:
traindata2 = pd.read_csv("no_na_SMOTENC.csv")

In [22]:
train2_X = traindata2.drop(["Is_Depressed"],axis = 1)
train2_y = traindata2["Is_Depressed"]

In [23]:
print(sorted(Counter(train2_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 5722), (1, 5722)]
[(0, 7166), (1, 148)]


In [83]:
# classifier2 = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=1),
#     n_estimators=1000
# )

# classifier2 = AdaBoostClassifier(
#     RandomForestClassifier(n_estimators = 200),
#     algorithm="SAMME",
#     n_estimators=200
# )

classifier2 = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 200),
    algorithm="SAMME",
    n_estimators=1000
)

In [84]:
scores2 = cross_val_score(classifier, test_X, test_y, cv=10, scoring='recall')
print(scores2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [85]:
classifier2.fit(train2_X, train2_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=200,
                          

In [86]:
predictions2 = classifier2.predict(test_X)

In [87]:
confusion_matrix(test_y, predictions2)

array([[7142,   24],
       [ 100,   48]], dtype=int64)

In [88]:
print("정확도",accuracy_score(test_y, predictions2))
print("Recall",recall_score(test_y, predictions2))
print("Precision",precision_score(test_y,predictions2))

정확도 0.9830462127426852
Recall 0.32432432432432434
Precision 0.6666666666666666


###

In [81]:
confusion_matrix(test_y, predictions2)

array([[7149,   17],
       [ 105,   43]], dtype=int64)

In [82]:
print("정확도",accuracy_score(test_y, predictions2))
print("Recall",recall_score(test_y, predictions2))
print("Precision",precision_score(test_y,predictions2))

정확도 0.9833196609242548
Recall 0.2905405405405405
Precision 0.7166666666666667


* 200 200

In [69]:
confusion_matrix(test_y, predictions2)

array([[7147,   19],
       [ 101,   47]], dtype=int64)

In [70]:
print("정확도",accuracy_score(test_y, predictions2))
print("Recall",recall_score(test_y, predictions2))
print("Precision",precision_score(test_y,predictions2))

정확도 0.9835931091058244
Recall 0.31756756756756754
Precision 0.7121212121212122


In [42]:
confusion_matrix(test_y, predictions2)

array([[7068,   98],
       [ 107,   41]], dtype=int64)

In [43]:
print("정확도",accuracy_score(test_y, predictions2))
print("Recall",recall_score(test_y, predictions2))
print("Precision",precision_score(test_y,predictions2))

정확도 0.9719715613891168
Recall 0.27702702702702703
Precision 0.2949640287769784
