# Import Python module 

In [2]:
import pandas as pd
import numpy as np

from collections import Counter


from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import accuracy_score,recall_score ,precision_score

## Test data 준비

In [5]:
testdata = pd.read_csv("feature_select_test_set.csv")

In [6]:
test_X = testdata.drop(["Is_Depressed"],axis = 1)
test_y = testdata["Is_Depressed"]

In [8]:
print(sorted(Counter(test_y).items()))

[(0, 7166), (1, 148)]


# 1. SMOTENC.csv

* read csv

In [66]:
traindata_smote = pd.read_csv("dataset_SMOTENC.csv")

In [68]:
traindata_smote.head()

BP7  D_1_1  BP1  LW_mp_a    ainc  DC6_dg  BP6_10  HE_wt   age  EC1_2  \
0  8.0    1.0  8.0    888.0   500.0     8.0     8.0   19.5   3.0    8.0   
1  2.0    4.0  3.0    999.0   314.0     0.0     2.0   66.9  76.0    5.0   
2  2.0    3.0  3.0    999.0   700.0     8.0     2.0   48.7  12.0    8.0   
3  8.0    2.0  3.0    888.0  1009.0     0.0     2.0   54.1  38.0    8.0   
4  2.0    2.0  1.0    888.0   500.0     8.0     2.0   45.8  14.0    8.0   

       ...       HE_obe  BM1_4  BO2_1  HE_Uph  EC_lgw_2  DE1_4  BD2_31  \
0      ...          9.0    8.0    8.0     9.0      88.0    8.0     8.0   
1      ...          2.0    0.0    1.0     6.5       7.0    8.0     4.0   
2      ...          9.0    0.0    4.0     6.0      88.0    8.0     8.0   
3      ...          2.0    1.0    3.0     5.0       3.0    8.0     3.0   
4      ...          9.0    1.0    1.0     6.5      88.0    8.0     8.0   

    BS6_2  DH2_dg  Is_Depressed  
0  8888.0     9.0             0  
1   480.0     1.0             0  
2  8888.0     8.0             0  
3  8888.0     9.0             0  
4  8888.0     8.0             0  

[5 rows x 58 columns]

In [69]:
train_smote_X = traindata_smote.drop(["Is_Depressed"],axis = 1)
train_smote_y = traindata_smote["Is_Depressed"]

In [71]:
print(sorted(Counter(train_smote_y).items()))

[(0, 28639), (1, 28639)]


In [72]:
# classifier = AdaBoostClassifier(
#     RandomForestClassifier(n_estimators = 10),
#     algorithm="SAMME",
#     n_estimators=200
# )

classifier_smote = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

In [73]:
scores = cross_val_score(classifier_smote, test_X, test_y, cv=10, scoring='recall')
print(scores)

[0.         0.         0.06666667 0.13333333 0.         0.
 0.         0.         0.         0.        ]


In [74]:
classifier_smote.fit(train_smote_X, train_smote_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [75]:
predictions_smote = classifier_smote.predict(test_X)

In [76]:
confusion_matrix(test_y, predictions_smote)

array([[7122,   44],
       [ 113,   35]], dtype=int64)

In [77]:
print("정확도",accuracy_score(test_y, predictions_smote))
print("Recall",recall_score(test_y, predictions_smote))
print("Precision",precision_score(test_y,predictions_smote))

정확도 0.978534317746787
Recall 0.23648648648648649
Precision 0.4430379746835443


# 2. dataset_edited.csv

In [30]:
traindata_edit = pd.read_csv("dataset_edited.csv")

In [31]:
train_edit_X = traindata_edit.drop(["Is_Depressed"],axis = 1)
train_edit_y = traindata_edit["Is_Depressed"]

In [33]:
print(sorted(Counter(train_edit_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 27183), (1, 615)]
[(0, 7166), (1, 148)]


In [41]:
# classifier2 = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=1),
#     n_estimators=1000
# )

# classifier2 = AdaBoostClassifier(
#     RandomForestClassifier(n_estimators = 200),
#     algorithm="SAMME",
#     n_estimators=200
# )

# classifier2 = AdaBoostClassifier(
#     RandomForestClassifier(n_estimators = 200),
#     algorithm="SAMME",
#     n_estimators=1000
# )

classifier_edit = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

In [42]:
scores_edit = cross_val_score(classifier_edit, test_X, test_y, cv=10, scoring='recall')
print(scores_edit)

[0.         0.         0.06666667 0.06666667 0.06666667 0.
 0.         0.         0.         0.        ]


In [45]:
classifier_edit.fit(train_edit_X, train_edit_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [46]:
predictions_edit = classifier_edit.predict(test_X)

In [47]:
confusion_matrix(test_y, predictions_edit)

array([[7159,    7],
       [ 128,   20]], dtype=int64)

In [48]:
print("정확도",accuracy_score(test_y, predictions_edit))
print("Recall",recall_score(test_y, predictions_edit))
print("Precision",precision_score(test_y,predictions_edit))

정확도 0.9815422477440525
Recall 0.13513513513513514
Precision 0.7407407407407407


# 3. dataset_condensed.csv

In [3]:
traindata_cond = pd.read_csv("dataset_condensed.csv")

In [4]:
train_cond_X = traindata_cond.drop(["Is_Depressed"],axis = 1)
train_cond_y = traindata_cond["Is_Depressed"]

In [9]:
print(sorted(Counter(train_cond_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 2442), (1, 615)]
[(0, 7166), (1, 148)]


In [23]:
classifier_cond = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

#200 1000


In [24]:
classifier_cond.fit(train_cond_X, train_cond_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [25]:
scores_cond = cross_val_score(classifier_cond, test_X, test_y, cv=10, scoring='recall')

In [26]:
print(scores_cond)

[0.         0.06666667 0.06666667 0.06666667 0.         0.
 0.         0.         0.         0.        ]


In [27]:
predictions_cond = classifier_cond.predict(test_X)

In [28]:
confusion_matrix(test_y, predictions_cond)

array([[7080,   86],
       [  86,   62]], dtype=int64)

In [29]:
print("정확도",accuracy_score(test_y, predictions_cond))
print("Recall",recall_score(test_y, predictions_cond))
print("Precision",precision_score(test_y,predictions_cond))

정확도 0.976483456385015
Recall 0.4189189189189189
Precision 0.4189189189189189


# 4. dataset_neighbour.csv

In [49]:
traindata_neigh = pd.read_csv("dataset_neighbour.csv")

train_neigh_X = traindata_neigh.drop(["Is_Depressed"],axis = 1)
train_neigh_y = traindata_neigh["Is_Depressed"]

print(sorted(Counter(train_neigh_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 27041), (1, 615)]
[(0, 7166), (1, 148)]


In [50]:
classifier_neigh = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

#200 1000


In [51]:
classifier_neigh.fit(train_neigh_X, train_neigh_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [53]:
scores_neigh = cross_val_score(classifier_neigh, test_X, test_y, cv=10, scoring='recall')

print(scores_neigh)

[0.         0.06666667 0.06666667 0.06666667 0.         0.
 0.         0.         0.         0.        ]


In [54]:
predictions_neigh = classifier_neigh.predict(test_X)

In [55]:
confusion_matrix(test_y, predictions_neigh)

array([[7159,    7],
       [ 127,   21]], dtype=int64)

In [56]:
print("정확도",accuracy_score(test_y, predictions_neigh))
print("Recall",recall_score(test_y, predictions_neigh))
print("Precision",precision_score(test_y,predictions_neigh))

정확도 0.9816789718348373
Recall 0.14189189189189189
Precision 0.75


# 5. dataset_onesided.csv

In [57]:
traindata_ones = pd.read_csv("dataset_onesided.csv")

train_ones_X = traindata_ones.drop(["Is_Depressed"],axis = 1)
train_ones_y = traindata_ones["Is_Depressed"]

print(sorted(Counter(train_ones_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 28356), (1, 615)]
[(0, 7166), (1, 148)]


In [58]:
classifier_ones = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

In [60]:
classifier_ones.fit(train_ones_X, train_ones_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [61]:
scores_ones = cross_val_score(classifier_ones, test_X, test_y, cv=10, scoring='recall')

print(scores_ones)

[0.         0.06666667 0.06666667 0.06666667 0.         0.
 0.         0.         0.         0.07142857]


In [62]:
predictions_ones = classifier_ones.predict(test_X)

In [63]:
confusion_matrix(test_y, predictions_ones)

array([[7161,    5],
       [ 130,   18]], dtype=int64)

In [64]:
print("정확도",accuracy_score(test_y, predictions_ones))
print("Recall",recall_score(test_y, predictions_ones))
print("Precision",precision_score(test_y,predictions_ones))

정확도 0.9815422477440525
Recall 0.12162162162162163
Precision 0.782608695652174


# 6.dataset_tomek.csv

In [78]:
traindata_tomek = pd.read_csv("dataset_tomek.csv")

train_tomek_X = traindata_tomek.drop(["Is_Depressed"],axis = 1)
train_tomek_y = traindata_tomek["Is_Depressed"]

print(sorted(Counter(train_tomek_y).items()))
print(sorted(Counter(test_y).items()))

[(0, 28368), (1, 615)]
[(0, 7166), (1, 148)]


In [79]:
classifier_tomek = AdaBoostClassifier(
    RandomForestClassifier(n_estimators = 500),
    algorithm="SAMME",
    n_estimators=1000
)

In [81]:
classifier_tomek.fit(train_tomek_X, train_tomek_y)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=500,
                          

In [82]:
scores_tomek = cross_val_score(classifier_tomek, test_X, test_y, cv=10, scoring='recall')

In [83]:
print(scores_tomek)

[0.         0.06666667 0.         0.06666667 0.         0.
 0.06666667 0.         0.         0.        ]


In [84]:
predictions_tomek = classifier_tomek.predict(test_X)

print(confusion_matrix(test_y, predictions_tomek))

print("정확도",accuracy_score(test_y, predictions_tomek))
print("Recall",recall_score(test_y, predictions_tomek))
print("Precision",precision_score(test_y,predictions_tomek))

[[7160    6]
 [ 130   18]]
정확도 0.9814055236532677
Recall 0.12162162162162163
Precision 0.75
